### ISSUE TITLE
Get theme from OS

### ISSUE THREAD

**Issue by DanInSpace104** [AnecFox/TimeCalcWeb#1]
Currently theme is light by default. Can you make it that it gets initial value from the Operation System (using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) for example), and then you can change it with dark/light switch.

**Comment by AnecFox** [comment]
Thank you, I will

**Comment by AnecFox** [comment]
Made✅
